core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('load-payment-form/', views.load_payment_form, name='load_payment_form'),
    path('error/', views.error_view, name='error'),
    # path('payment/notification/', views.payment_notification, name='payment_notification'),
    path('payment-notification/', views.payment_notification, name='payment-notification'),
    path('payment-response/', views.payment_response, name='payment-response'),
]

home/models.py
from django.db import models
from orders.models import SimpleOrder


class PaymentNotification(models.Model):
    order = models.ForeignKey(
        SimpleOrder,
        on_delete=models.CASCADE,
        related_name='notifications',
        default=1)  # ID of the default SimpleOrder instance
    txId = models.CharField(max_length=50)  # The unique identifier for the transaction in the BOIPA Gateway
    merchantTxId = models.CharField(max_length=50)  # The merchant’s reference for the transaction provided in the
    country = models.CharField(max_length=2, null=True, blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    currency = models.CharField(max_length=3, null=True, blank=True)
    action = models.CharField(max_length=10, null=True, blank=True)
    auth_code = models.CharField(max_length=10, null=True, blank=True)  # Extracted from paymentSolutionDetails
    acquirer = models.CharField(max_length=100, null=True, blank=True)
    acquirerAmount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    merchantId = models.CharField(max_length=50, null=True, blank=True)
    brandId = models.CharField(max_length=50, null=True, blank=True)
    customerId = models.CharField(max_length=50, null=True)
    acquirerCurrency = models.CharField(max_length=3, null=True, blank=True)
    paymentSolutionId = models.IntegerField(null=True, blank=True)
    status = models.CharField(max_length=50, null=True, blank=True)


    def __str__(self):
        return self.txId

orders/models.py
from django.db import models

class SimpleOrder(models.Model):
    customer_name = models.CharField(max_length=100, verbose_name="Customer Name", default="Test")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created")
    updated = models.DateTimeField(auto_now=True, verbose_name="Updated")
    paid = models.BooleanField(default=False, verbose_name="Paid")
    total_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Total Price")

    class Meta:
        ordering = ('-created',)  # Orders records by creation time in descending order

    def __str__(self):
        return f'Order {self.id} - {self.customer_name}'

refunds/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.http import HttpResponse, QueryDict
from django.db import transaction
from django.views.decorators.csrf import csrf_exempt
import logging
from .models import PaymentNotification, SimpleOrder
from .payment_functions import get_boipa_session_token  # If external functions are used
from django.conf import settings

# Initialize logging
payments_logger = logging.getLogger('payments')


def home(request):
    # Render the home page. Additional context can be passed if needed.
    return render(request, 'home.html')


def load_payment_form(request):
    # Create an order
    order = SimpleOrder(
        customer_name='John Doe',
        paid=False,
        total_price=99.99
    )
    order.save()
    total_price = 199.00
    order_id = order.pk
    token = get_boipa_session_token(request, order_id, total_price)
    if token is None:
        return render(request, 'error.html', {'error': 'Unable to obtain session token.'})

    # Construct the HPP URL with the obtained token and include integrationMode
    hpp_url = settings.HPP_FORM + f"?token={token}&merchantId={settings.BOIPA_MERCHANT_ID}&integrationMode=Standalone"

    # Redirect user to the HPP URL
    return redirect(hpp_url)


def error_view(request):
    # Example error handling logic
    error_message = "An unexpected error has occurred."
    return render(request, 'error.html', {'error_message': error_message})


def payment_response(request):
    # Assuming 'result' is a parameter indicating the payment outcome
    payments_logger.debug(f"Received payment response: {request.GET.dict()}")
    result = request.GET.get('result')
    merchantTxId = request.GET.get('merchantTxId')
    if result == "success":
        payments_logger.info(f"Payment for {merchantTxId} processed successfully.")
        # Message
        context = {
            'title': "Payment Success",
            'message': "Your payment has been successfully processed.",
            'order_ref': merchantTxId,
            'result': result,
        }
        return render(request, 'payment_success.html', context)

    elif result == "failure":
        # Logic for failed payment
        payments_logger.warning(f"Payment for {merchantTxId} failed.")
        context = {
            'title': "Payment Failure",
            'message': f"Payment failed",
            'order_ref': merchantTxId,
            'result': result,
        }
        return render(request, 'payment_failure.html', context)

    else:
        # Handle unknown result
        return render(request, 'error.html', {'message': "Unknown payment response."})


@csrf_exempt  # Disable CSRF protection for this endpoint
def payment_notification(request):
    if request.method == 'POST':
        payments_logger.debug(f"Received payment notification: {request.POST.dict()}")
        # Parse the URL-encoded form data
        data = QueryDict(request.body)
        merchantTxId = data.get('merchantTxId')
        source_prefix, order_id_str = merchantTxId.split("_", 1)
        order_id = int(order_id_str)

        # Update Order
        with transaction.atomic():
            order = SimpleOrder.objects.get(id=order_id)
            order.paid = True
            order.save()
        # Store Notification Details
        with transaction.atomic():
            PaymentNotification.objects.create(
                order=order,
                txId=data.get('txId'),
                merchantTxId=data.get('merchantTxId'),
                country=data.get('country'),
                amount=data.get('amount'),
                currency=data.get('currency'),
                action=data.get('action'),
                # Assuming auth_code and other details are extracted correctly from paymentSolutionDetails or similar
                # auth_code=data.get('auth_code'),
                acquirer=data.get('acquirer'),
                acquirerAmount=data.get('acquirerAmount'),
                merchantId=data.get('merchantId'),
                brandId=data.get('brandId'),
                customerId=data.get('customerId'),
                acquirerCurrency=data.get('acquirerCurrency'),
                paymentSolutionId=data.get('paymentSolutionId'),
                status=data.get('status'),
            )
            payments_logger.info("Payment processed successfully.")
            # Return a successful HTTP response
            return HttpResponse('Payment processed successfully', status=200)

    # If not a POST request, or if other issues are encountered
    return HttpResponse('Invalid request', status=400)

orders/views.py
from django.shortcuts import render

# Create your views here.

refunds/views.py
from django.shortcuts import render, redirect
from .models import Refund
from .forms import RefundForm
from django.contrib import messages

def process_refund(request):
    if request.method == 'POST':
        form = RefundForm(request.POST)
        if form.is_valid():
            # Process refund here (e.g., calling an external API)
            # And then create a Refund record
            Refund.objects.create(
                transaction_id=form.cleaned_data['transaction_id'],
                amount=form.cleaned_data['amount'],
                reason=form.cleaned_data['reason']
            )
            messages.success(request, 'Refund processed successfully.')
            return redirect('some-view-name')
    else:
        form = RefundForm()
    return render(request, 'refunds/refund_form.html', {'form': form})

home/templates/demo_token.html
{% extends '_base.html' %}
{% block title %}BOIPA Token Demo{% endblock %}

{% block content %}
<div class="container mx-auto px-4 py-8">
    <h1 class="text-3xl font-bold text-center text-blue-600 mb-4">BOIPA Session Token</h1>
    <p class="text-xl text-center text-gray-800 bg-gray-200 p-4 rounded-lg shadow">
        The session token is: <span class="font-mono font-semibold">{{ token }}</span>
    </p>
</div>
{% endblock %}

home/templates/error.html
{% extends '_base.html' %}

{% block title %}Error Occurred{% endblock %}

{% block content %}
<div class="min-h-screen flex flex-col items-center justify-center bg-gray-100">
    <div class="max-w-md w-full bg-white rounded-lg shadow-md p-6">
        <h2 class="text-xl font-semibold text-gray-900">Error</h2>
        <p class="mt-4 text-sm text-gray-600">
            We're sorry, but something went wrong. Please try again later.
        </p>
        {% if error_message %}
            <div class="mt-3 text-sm text-red-500">
                {{ error_message }}
            </div>
        {% endif %}
        <div class="mt-6">
            <a href="{% url 'home' %}" class="text-indigo-600 hover:text-indigo-500">Go back to the homepage</a>
        </div>
    </div>
</div>
{% endblock %}

home/templates/home.html
{% extends '_base.html' %}
{% load static %}
{% block title %}BOIPA | Home{% endblock %}

{% block content %}
{# <img src="{% static 'img/worldmap.jpg' %}" alt="World Map" class="absolute w-full h-full object-cover"> #}

<div class="flex items-center justify-center h-screen w-full">
    <div>
        <h1 class='text-center text-5xl font-bold leading-tight text-white font-serif'>Welcome to BOIPA</h1>
        <h2 class='text-3xl text-gray-500 text-center italic'>A World Standard</h2>
        <p class='text-2xl text-gray-300 text-justify text-center px-4 md:px-6 lg:px-24 py-16'>BOIPA is a test site for eCommerce</p>
        <div class="mt-8">
            <h1 class='text-center text-4xl font-bold text-blue-500'>Environment Variable</h1>
            <p class='text-center text-3xl text-blue-400'>MERCHANT ID:</p>
        </div>
    </div>
</div>

{% endblock %}

home/templates/payment_failure.html
<!-- templates/payment_failure.html -->
{% extends '_base.html' %}
{% load static %}
{% block title %}BOIPA | Payment Failure{% endblock %}

{% block content %}
<div class="min-h-screen bg-gray-100 flex flex-col items-center justify-center">
    <div class="bg-white p-8 rounded-lg shadow-md max-w-md mx-auto">
        <h1 class="text-2xl font-bold text-red-600 mb-4">Payment Failure</h1>
        <p class="mb-2">Unfortunately, your payment could not be processed.</p>
        <p class="mb-2"><span class="font-semibold">Order ID:</span> {{ order_ref }}</p>
        <p class="mb-4"><span class="font-semibold">Reason:</span> {{ message }}</p>
        <a href="{% url 'home:home' %}" class="inline-block bg-blue-500 text-white font-semibold px-6 py-2 rounded
        hover:bg-blue-600 transition ease-in-out duration-150">Return to Home</a>
    </div>
</div>
{% endblock %}

home/templates/payment_form.html
{% extends '_base.html' %}

{% block title %}Payment Form{% endblock %}

{% block content %}
<div class="max-w-4xl mx-auto p-4">
    <h1 class="text-xl font-semibold mb-4">Complete Your Payment</h1>
    <div class="border-2 border-gray-200">
        <!-- The iframe src is dynamically set to the HPP URL -->
        <iframe src="{{ hpp_url }}" class="w-full" style="height: 500px;" frameborder="0"></iframe>
    </div>
</div>
{% endblock %}

home/templates/payment_success.html
<!-- templates/payment_success.html -->
{% extends '_base.html' %}
{% load static %}
{% block title %}BOIPA | Payment Success{% endblock %}

{% block content %}
<div class="min-h-screen bg-gray-100 flex flex-col items-center justify-center">
    <div class="bg-white p-8 rounded-lg shadow-md max-w-md mx-auto">
        <h1 class="text-2xl font-bold text-green-600 mb-4">Payment Success</h1>
        <p class="mb-2">Your payment has been successfully processed.</p>
        <p class="mb-2"><span class="font-semibold">Order ID:</span> {{ order_ref }}</p>
        <p class="mb-4"><span class="font-semibold">Status:</span> {{ result }}</p>
        <a href="{% url 'home:home' %}" class="inline-block bg-blue-500 text-white font-semibold px-6 py-2 rounded
        hover:bg-blue-600 transition ease-in-out duration-150">Return to Home</a>
    </div>
</div>
{% endblock %}

templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="https://cdn.tailwindcss.com"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Django Project</title>
   <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.13.5/dist/cdn.min.js"></script>
    <!-- Include Tailwind CSS -->
    {#    CSS Styles #}

    {#    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">#}
</head>
<body class="bg-black">


<!-- Navbar -->
{% include '_navbar.html' %}

<!-- Main Content -->
<main>
    {% block content %}
        <!-- Content goes here -->
    {% endblock %}
</main>

</body>
</html>

templates/_navbar.html
{% load static %}

<nav class="bg-gray-800">
    <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
        <div class="flex items-center justify-between h-16">
            <!-- Left side - Logo and Navigation Links -->
            <div class="flex items-center">
                <div class="hidden sm:block sm:ml-6">
                    <div class="flex space-x-4">
                        <!-- Correctly reference your navigation links -->
                        <a href="/" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md
                        text-sm font-medium">Home</a>
                          <a href="/load-payment-form/" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md
                        text-sm font-medium">Payment</a>
                        <a href="/admin/" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md
                        text-sm font-medium">admin</a>
                        <!-- Insert additional navigation links here as needed -->
                    </div>
                </div>
            </div>
            <!-- Right side of the navbar could go here -->
        </div>
    </div>
</nav>